### ISSUE TITLE
Docs versioning

### ISSUE THREAD

**Issue by xfra35** [F3Community/F3com-data#83]
Hi guys,

3.6 has been released and there are quite some changes to bring to the docs.

Maybe it's time to decide how the website content should follow the framework history:
1. should it match the latest release only? (that's how it's been working so far)
2. or should it keep a history of changes? (that could be helpful for migrations and/or supporting older releases)

If we stick to the first strategy, we'd better create a dev branch that we could feed until the next release.

If we go for the second strategy, we need to decide how to display the docs history. It could be a small changelog for each modified API method, like on [php.net](http://php.net/), or a general version selector, like on [dev.mysql.com](https://dev.mysql.com/doc/).

**Comment by Joseffb** [comment]
Can we do second option and use a wiki system with revision tracking?

Please pardon any typos as this email is sent from my iPhone

**Comment by ikkez** [comment]
I'm for a version selector. let's just wrap the whole repo contents in another folder for each version number. git is the revision/versioning tracking, isn't it? For the website we only need to add a selector and adjust the load paths. easy.

**Comment by Joseffb** [comment]
I agree; I later thought about the use case of a Dev on an older version looking for docs specific to their older version and the pain it would be to look into revision for that older doc.

I think it's a good idea to route it via version but I think the entire index should be to that version rather then a page about the function and how it's evolved and differences between versions like Drupal does. Wordpress does a decent job of this.

In the past, I've run into looking up function calls for Drupal and being confused as to which version they are referring to. 

Please pardon any typos as this email is sent from my iPhone

**Comment by xfra35** [comment]
Done here: https://github.com/F3Community/F3com/commit/842ffac19d1e39e22554cc54f2d4a1bfdebf197a
