### ISSUE TITLE
Tag the GitHub repository

### ISSUE THREAD

**Issue by Rayne** [F3Community/F3com-data#85]
I propose to add the following tags to the repository:

* `fat-free-framework`
* `documentation`

and perhaps

* `php` because it's the documentation for a PHP framework

I would have added the tags if I had the permission to do so.

The tags could also be added to `fatfree` and `fatfree-core`. I'm not sure if it's necessary to tag `F3com`.

**Comment by xfra35** [comment]
Done. Thanks for the heads up 👍
