### ISSUE TITLE
Documentation for the RFC6455 WebSocket Server (since 3.6.0)

### ISSUE THREAD

**Issue by Rayne** [F3Community/F3com-data#87]
The WebSocket Server isn't documented yet.

It could be possible that I am remembering it wrong, but didn't @bcosca post an example somewhere?

**Comment by xfra35** [comment]
Well there's the unit test:
https://github.com/bcosca/fatfree/blob/dev/app/ws.php
https://github.com/bcosca/fatfree/blob/dev/ui/ws.htm
https://github.com/bcosca/fatfree/blob/dev/ui/layout.htm
https://github.com/bcosca/fatfree/blob/dev/rfc6455.php

Start the web server with either:
`php /path/to/rfc6455.php` (foreground)
or
`php -q /path/to/rfc6455.php >> /path/to/rfc6455.log & disown` (background)

**Comment by Rayne** [comment]
Inspired by #108, I continued with the documentation of the WebSocket implementation. I will commit the documentation this weekend.

- [X] Inspect #108
- [X] Create the `WebSocket` page in [F3com](https://github.com/F3Community/F3com)
- [X] Write documentation for `\CLI\WS` and `\CLI\Agent`
  - [X] Constructor
  - [X] Methods
  - [X] Event Handlers
  - [X] Agent
- [ ] Create a repository for the implementation example or add it to the documentation page

**Comment by Rayne** [comment]
The repository with the example implementation: https://github.com/F3Community/websocket-example
