### ISSUE TITLE
8x Errors 404

### ISSUE THREAD

**Issue by emanwebdev** [F3Community/F3com-data#96]
Hi all, 
Starting a new project served by F3  

hence 1st thing 1st, reading the doc again 

While browsing the doc found a couple of 404 as per:

https://www.drlinkcheck.com/results/4ef435/1/broken

Nothing serious, most old plugins and the like

Thanks a lot for F3

**Comment by sn0opy** [comment]
Fixed all of them that needed to be fixed. Thanks!

**Comment by xfra35** [comment]
https://github.com/blo4r/fatfree-blog is still there >> https://github.com/jlopinto/fatfree-blog
