### ISSUE TITLE
Document system variable SEED

### ISSUE THREAD

**Issue by Rayne** [F3Community/F3com-data#97]
- [New framework variable: SEED](https://slides.com/ikkez/fat-free-v3-6#/11)
- [Usage of SEED in CSRF tokens](https://github.com/bcosca/fatfree-core/commit/3446a34c3e8a7249e70e687eda9c70b3f4ca9ce2#diff-40b4d8fe5bab813702623528aea4776eR207)

**Comment by ikkez** [comment]
done at https://github.com/F3Community/F3com-data/commit/da7f7994d0fa82f3d58710d9fa5aeb26e87e00f8

**Comment by Rayne** [comment]
Nice :+1:
